//
// Created by PinkySmile on 04/11/2020.
//

#ifndef HISOUTENSOKUDISCORDINTEGRATION_GETPUBLICIP_HPP
#define HISOUTENSOKUDISCORDINTEGRATION_GETPUBLICIP_HPP

const char *getMyIp();
const char *getMyIpv6();
bool isIpv6Available();

#endif // HISOUTENSOKUDISCORDINTEGRATION_GETPUBLICIP_HPP
